### ISSUE TITLE
Datastore beta3?

### ISSUE THREAD

**Issue by FaisalAbid** [dart-lang/googleapis#10]
Any plans to support beta3 of the datastore api?

**Comment by sgjesse** [comment]
There are currently no concrete plans. According to https://cloudplatform.googleblog.com/2016/04/Google-Cloud-Datastore-gets-faster-cross-platform-API.html the v1beta2 API will be turned down by end of September.

**Comment by FaisalAbid** [comment]
Thanks. I guess as long as we are able to use the new API before v2 ends we
should be good :)

On Mon, Apr 25, 2016, 4:58 AM Søren Gjesse <notifications@github.com> wrote:

> There are currently no concrete plans. According to
> https://cloudplatform.googleblog.com/2016/04/Google-Cloud-Datastore-gets-faster-cross-platform-API.html
> the v1beta2 API will be turned down by end of September.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/googleapis/issues/10#issuecomment-214216371>
>
-- 

Sent from my phone

**Comment by FaisalAbid** [comment]
Is there any plans to get this updated to V1 final? Nervous to port over some code to Datastore because of this.

**Comment by mkustermann** [comment]
The [datastore:v1 API](https://www.dartdocs.org/documentation/googleapis/0.37.0/googleapis.datastore.v1/googleapis.datastore.v1-library.html) has been added to `package:googleapis` some time ago.
