### ISSUE TITLE
Broken link in pub.dev documentaion

### ISSUE THREAD

**Issue by katutxakurra** [dart-lang/googleapis#100]
This is not an issue in the github repo but there is a broken link in 
https://pub.dev/packages/googleapis/versions/0.55.0#-example-tab- 
where the example points to
https://github.com/dart-lang/googleapis/blob/master/example/main.dart
but it should point to 
https://github.com/dart-lang/googleapis/blob/master/resources/googleapis/examples/main.dart

**Comment by kevmoo** [comment]
Our repository has changed around. This should be fixed in the next package publish.

**Comment by kevmoo** [comment]
Need to update our repository!
