### ISSUE TITLE
People API is missing listDirectoryPeople and searchDirectoryPeople

### ISSUE THREAD

**Issue by caydenm** [dart-lang/googleapis#106]
Hello Dart team, 

It appears the People API is missing a few methods that are included in the V1 Rest API, namely listDirectoryPeople and searchDirectory people.

https://developers.google.com/people/api/rest/v1/people/listDirectoryPeople
https://developers.google.com/people/api/rest/v1/people/searchDirectoryPeople

It would be amazing if these were added.

**Comment by kevmoo** [comment]
Fixed in v1 https://pub.dev/documentation/googleapis/latest/people.v1/PeopleResource-class.html
