### ISSUE TITLE
Any BigQuery specific documentation? 

### ISSUE THREAD

**Issue by Pauljohnson78** [dart-lang/googleapis#107]
I'm having real trouble finding any information relating to BigQuery and Dart. I'm pretty new to all this and am running out of things to try.

Any advice would be really helpful.

**Comment by kevmoo** [comment]
This is the place to start with using via Dart - https://pub.dev/documentation/googleapis/latest/googleapis.bigquery.v2/BigqueryApi-class.html

We are going to roll out an update soon that will improve our documentation.

These APIs are auto-generated, so we don't have specific help for BigQuery specifics.

I'd start here: https://cloud.google.com/bigquery/

**Comment by aalokdosii** [comment]
updated link : https://pub.dev/documentation/googleapis/latest/bigquery.v2/bigquery.v2-library.html
