### ISSUE TITLE
Checked mode: type 'int' is not a subtype of type 'double' of 'value'

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/googleapis#11]
I try to use the Sheet API v4. In checked mode I got this error with googleapis v0.28.0:

```
type 'int' is not a subtype of type 'double' of 'value' where
  int is from dart:core
  double is from dart:core

package:googleapis/sheets/v4.dart 2396:15  Color.blue=
package:googleapis/sheets/v4.dart 2409:7   Color.Color.fromJson
package:googleapis/sheets/v4.dart 2053:29  CellFormat.CellFormat.fromJson
package:googleapis/sheets/v4.dart 5889:27  SpreadsheetProperties.SpreadsheetProperties.fromJson
package:googleapis/sheets/v4.dart 5813:24  Spreadsheet.Spreadsheet.fromJson
package:googleapis/sheets/v4.dart 218:41   SpreadsheetsResourceApi.get.<fn>
```

with this program

``` dart
main() async {
  var accountCredentials =
      new ServiceAccountCredentials.fromJson({
    "type": "service_account",
    "project_id": "xxx",
    "private_key_id": "xxx",
    //...
  });
  var client = await clientViaServiceAccount(
      accountCredentials, ['https://www.googleapis.com/auth/spreadsheets']);

  var sheetApi = new SheetsApi(client);
  await sheetApi.spreadsheets.get('xxx');

  client.close();
}
```

Thanks

**Comment by josemvidal** [comment]
I am getting the same error, with googleapis 0.50.2

```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
type 'int' is not a subtype of type 'double' where
   int is from dart:core
   double is from dart:core
 
 #0      new Color.fromJson (package:googleapis/sheets/v4.dart:4509:19)
 #1      new CellFormat.fromJson (package:googleapis/sheets/v4.dart:3958:29)
 #2      new SpreadsheetProperties.fromJson (package:googleapis/sheets/v4.dart:9723:27)
 #3      new Spreadsheet.fromJson (package:googleapis/sheets/v4.dart:9632:24)
 #4      SpreadsheetsResourceApi.get.<anonymous closure>(package:googleapis/sheets/v4.dart:247:41)
 #5      _RootZone.runUnary (dart:async/zone.dart:1381:54)
 #6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
```

Is there a workaround? I'm using flutter.

**Comment by miyoyo** [comment]
Easiest workaround I found is just copy/pasting sheets/v4.dart into a local project file and adding .toDouble() at the end of the incriminated _json["*"] methods

**Comment by mkustermann** [comment]
@jakobr-google Would you be interested in looking at this?

**Comment by wilidga** [comment]
//this help to me with read json from another api. 

double temp = weatherData['main']['temp'].toDouble();

#The Complete Flutter Development Bootcamp Using Dart

**Comment by jdeltoft** [comment]
the .toDouble() fixed this for me.  Just a note though, in Android Studio autocomplete of methods only shows .toString().  You just have to boldly ignore the suggestions!

**Comment by scsfwgy** [comment]
can`r cast int to double ?why ？

**Comment by eernstg** [comment]
(This issue is closed, and StackOverflow is a better place for questions. Anyway, ..)

A Dart type cast and type test (`as` respectively `is`) will check whether a given entity has the requested type, it _never_ changes the entity itself. So if you have an `int` and you need a `double`, you need to perform an actual computation on it, like `myInt.toDouble()`.

There's a tricky exception: For performance reasons, Dart-on-the-web uses JavaScript numbers. So every number (of type `int` as well as type `double`) has the same representation, and a type cast will actually suffice to obtain a value of type `double` from a given value of type `int`. A cast in the opposite direction may fail (e.g., `3.18` has type `double`, but `3.18 as int` will throw at run time because this is not one of those double values that is also an integer).

**Comment by scsfwgy** [comment]
But,when parse json,this is a tough thing,because some default value is 0,which is double type...

**Comment by eernstg** [comment]
It's not quite obvious to me which situation you are thinking about. But if you have a string (say, '0' or '47.432'), and your parser delivers an object (an `int` respectively a `double`), and you store that in a variable `num v;`, then you can use `v.toDouble()` to obtain an object of type `double`. So you'd invoke the method `toDouble()` at the point where you would otherwise put a type cast.

**Comment by zyllus17** [comment]
> //this help to me with read json from another api.
> 
> double temp = weatherData['main']['temp'].toDouble();
> 
> #The Complete Flutter Development Bootcamp Using Dart

It then converts the Celsius to Kelvin though I have put metrics measurement, can you help me out?

**Comment by KalpaD98** [comment]
have you tried`  int temp  `
you just need a whole number to display the temperature

**Comment by aerosasi** [comment]
> //this help to me with read json from another api.
> 
> double temp = weatherData['main']['temp'].toDouble();
> 
> #The Complete Flutter Development Bootcamp Using Dart

Thanks man ! It worked !

**Comment by aerosasi** [comment]
> > //this help to me with read json from another api.
> > double temp = weatherData['main']['temp'].toDouble();
> > #The Complete Flutter Development Bootcamp Using Dart
> 
> It then converts the Celsius to Kelvin though I have put metrics measurement, can you help me out?

make sure you have put units=metric in the end of the api url

**Comment by scsfwgy** [comment]
or like this ?

`
class ParseUtil {
  static double parseDouble(dynamic data) {
    String str = data?.toString() ?? "0";
    double num = double.parse(str);
    return num;
  }

  static int parseInt(dynamic data, {bool floor = true}) {
    double core = parseDouble(data);
    return floor ? core.floor() : core.ceil();
  }

  static String parseString(dynamic data) {
    String str = data?.toString() ?? "";
    return str;
  }
}

`

**Comment by Marflage** [comment]
> 
> 
> //this help to me with read json from another api.
> 
> double temp = weatherData['main']['temp'].toDouble();
> 
> #The Complete Flutter Development Bootcamp Using Dart

Or you could just remove the temp variable entirely and directly assign the data to temperature. That way you would not be converting temp to an integer and then assigning it to temperature. I did that and it worked, though your solution works too.

**Comment by guvanch07** [comment]
handle if is null

json["*"] != null ? json["*"].toDouble() : 0   // 0 is data is null
