### ISSUE TITLE
Migration to null safety.

### ISSUE THREAD

**Issue by Jonas-Sander** [dart-lang/googleapis#119]
[Null safety seems to be in beta](https://medium.com/flutter/announcing-dart-null-safety-beta-4491da22077a) now.
Will this package be migrated?

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/googleapis/commit/d0b71273bb7e33af96b526170b5e984b2bacae14

hope to publish soon!

**Comment by remonh87** [comment]
@kevmoo is there any dependency that prevents from publishing? Would be great to be able to have null-safe generated apis. I am happy to help out (or test)

**Comment by kevmoo** [comment]
@remonh87 – publishing today!

**Comment by kevmoo** [comment]
@remonh87 – now published!
