### ISSUE TITLE
Add Firebase Realtime Database api

### ISSUE THREAD

**Issue by unco-games** [dart-lang/googleapis#12]
There is no complete documentation about access to Realtime Database from standalone Dart application.

**Comment by mkustermann** [comment]
There are two firebase related apis in `package:googleapis` at the moment:

  * [googleapis.firebasedynamiclinks.v1](https://www.dartdocs.org/documentation/googleapis/0.37.0/googleapis.firebasedynamiclinks.v1/googleapis.firebasedynamiclinks.v1-library.html)
  * [googleapis.firebaserules.v1](https://www.dartdocs.org/documentation/googleapis/0.37.0/googleapis.firebaserules.v1/googleapis.firebaserules.v1-library.html)

The `package:googleapis` and `package:googleapis_beta` contain only the APIs which are exposed via the discovery service and we roll it every couple of weeks.

If these two APIs are not what you were looking for, then the API you mentioned is probably not exposed via the discovery service and it will not be included in our rolls.

Hopefully this will help you.
