### ISSUE TITLE
Firestore : projects.databases.documents.batchWrite is missing

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/googleapis#120]
Hi, I'm needing `batchWrite` functionality as described here:
https://firebase.google.com/docs/firestore/reference/rest/v1/projects.databases.documents/batchWrite

But it appears to be missing? I see `batchGet` is available. I'm using version 0.55

**Comment by kevmoo** [comment]
Added in v1 https://pub.dev/documentation/googleapis/latest/firestore.v1/ProjectsDatabasesDocumentsResource/batchWrite.html
