### ISSUE TITLE
Drive API v3: File.iconLink returns null

### ISSUE THREAD

**Issue by anshgwash** [dart-lang/googleapis#123]
Some metadata returns a value, for example, File.name correctly returns the name of the File on Google Drive. However, File.iconLink returns null. Is this a known issue, and is there a workaround?

**Comment by kevmoo** [comment]
we just forward on the data we get. Unless you have a clear notion that this is a bug in our implementation, I'm going to close.

I'd start here https://developers.google.com/drive/api/v3/about-sdk if you have further questions
