### ISSUE TITLE
GcsData.path is missing in StorageTransfer

### ISSUE THREAD

**Issue by nilsreichardt** [dart-lang/googleapis#131]
# Description
Hi! In the StorageTransfer API `GscData.path` is missing. There is only `GscData.name` but as you can see in the documentation `path` is missing in the Dart library:

## Documentation
![image](https://user-images.githubusercontent.com/24459435/105491363-74e68600-5cb6-11eb-8055-30ffc0e79f65.png)
https://cloud.google.com/storage-transfer/docs/reference/rest/v1/TransferSpec#gcsdata

# Dart code
![image](https://user-images.githubusercontent.com/24459435/105491391-816ade80-5cb6-11eb-966d-fc354f0a5a85.png)

**Comment by kevmoo** [comment]
This is fixed now - https://pub.dev/documentation/googleapis/latest/storagetransfer.v1/GcsData-class.html

**Comment by nilsreichardt** [comment]
Thanks! 🙏
