### ISSUE TITLE
discoveryapis_common: each service call is generating a separate http OPTIONS and POST round-trip

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/googleapis#136]
See https://github.com/dart-lang/dart-pad/issues/385 for more details. We've worked around the issue in our client. We may want to move a more permanent fix into `src/clients.dart/simpleRequest` or into the `discoveryapis_generator` generated library?

**Comment by kevmoo** [comment]
I can't see this double-request stuff. Let me know if it's still an issue!
