### ISSUE TITLE
Is there anyone that monitors these issues?

### ISSUE THREAD

**Issue by goranj** [dart-lang/googleapis#16]

**Comment by zoechi** [comment]
They might monitor incoming pull requests ;-)

**Comment by goranj** [comment]
Are you suggesting that I, or rather someone (not Google) with the necessary skills, should fix problems in this library? And if so, can I pay someone to do that?

(I'm struggling to _use_ tools like Dart and Google API to help my customers (who use G Suite) solve business problems. But I'm not qualified to _build_ the tools.)

**Comment by zoechi** [comment]
@goranj sure. In the "worst case" you also can just create a copy of the package where you fix the issues and use that copy instead (in case nobody would react to pull request, which would be surprising)

**Comment by goranj** [comment]
Thanks @zoechi!
I'll make a copy of the package and try to fix what is missing. This is a bit above my skills and I have only a vague idea of "pull requests". But that might change :)

**Comment by zoechi** [comment]
Usually you'll get good feedback for pull requests how to improve if something is not like it should be.

**Comment by mkustermann** [comment]
Very sorry, my github account was not watching this repository!

This repository should normally not be used by anybody except us, who roll/update `package:googleapis` and `package:googleapis_beta`.

The [discovery_generator](https://github.com/dart-lang/discoveryapis_generator) is what normal users might want to use.

Will close this issue.
