### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by bdlindsay** [dart-lang/googleapis#194]
From a sound null safety Flutter code base calling `obtainAccessCredentialsViaUserConsent` or `obtainAccessCredentialsViaUserConsentManual` from `googleapis_auth: ^1.1.0` is immediately throwing an error that just says `Null check operator used on a null value` without any further explanation. Is there an issue with the null safe version of the googleapis_auth package?

Flutter doctor:
```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.1)
[✓] Connected device (4 available)
```

**Comment by bdlindsay** [comment]
It looks like this error might be caused by: `Uri.encodeQueryComponent(clientId.secret!)` in `auth_code.dart`. Maybe a better error message besides force unwrapping an nullable would be good.

**Comment by bdlindsay** [comment]
It seems like passing an empty string as clientSecret will get past this error and also authenticate correctly, maybe the change could be `Uri.encodeQueryComponent(clientId.secret ?? '')` instead so that `ClientId('[some-client-id]', null)` is still available as an option for users of the google oauth package.

**Comment by jonasfj** [comment]
@bdlindsay curious, where do use `null` as a secret? Is that ever valid in production?

Are you manually doing `ClientId('[some-client-id]', null)` and if so why?  -- just curious at what flow I'm not understanding :D

**Comment by bdlindsay** [comment]
I believe it is. I was in the process of rewriting a legacy mobile app to flutter and the previous code didn't ever use a client secret. I'm assuming because it's redirecting for someone's personal gmail account that it's just using the user/pass credentials so it never has a need for a client secret. I can successfully authenticate and send and retrieve data from a user's google drive by just passing the client id.

**Comment by kevmoo** [comment]
I tried this new flow.

We no longer crash in Dart code, but I always get `Response was 400. Error: invalid_request client_secret is missing`

What type of OAuth credential are you using @bdlindsay ?

![image](https://user-images.githubusercontent.com/17034/111396907-4618da80-867d-11eb-864e-aed2b2cc4767.png)

**Comment by bdlindsay** [comment]
I believe it would be for iOS and Android application types
