### ISSUE TITLE
googleapis_auth: Add `clientUsingHeaders` – allow using client via Flutter & pkg:google_sign_in

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/googleapis#202]
The impl is pretty easy

**Comment by jonasfj** [comment]
Why not put this in pkg:google_sign_in

Or in package:http, or in something like package:http_utils

**Comment by kevmoo** [comment]
Wow. That's actually a very good idea

**Comment by kevmoo** [comment]
Better to just put this in google_sign_in!

**Comment by kevmoo** [comment]
See https://github.com/flutter/flutter/issues/78090
