### ISSUE TITLE
Google Drive v3 API: Add in documentation that $fields expects `files/starred` format, not `starred` format

### ISSUE THREAD

**Issue by maryx** [dart-lang/googleapis#23]
See https://stackoverflow.com/questions/47148937/how-to-set-the-fields-parameter-in-the-google-drive-googleapis-v3-in-dart/47149162#47149162 for more context.

Essentially, the web `Try this API` form at https://developers.google.com/drive/v3/reference/files/list is different enough from the Dart implementation that first-time users may get very confused.

Web version for list():
- Press the `Try It` button, press `Show standard parameters`, and note the `fields` param.
- `fields` can be set by just typing in a comma separated string of fields, such as `starred,createdTime,webContentLink`. 

Dart v3 version for list():
- `fields` isn't recognized as a query param; only by digging into the code do you find that it should be `$fields`
- We also have to pass in the resource type when setting the `$fields`, i.e. `files/starred,files/createdTime,files/webContentLink`. This isn't mentioned in the documentation. When you only pass in `starred,createdTime,webContentLink`, the 400 error that returns is confusing - it says `DetailedApiRequestError(status: 400, message: Invalid field selection starred)`, yet the web documentation lists `starred` as a field. Appending `files/` also seems redundant since we're calling the *Files* resource's list(), not a generic list() call.

Update: It turns out that I had been testing using Files.get() on the web API explorer, where you don't have to specify the resource (`fields=starred`), but in the Files.list() web API explorer, you do (`fields=files/starred`). This is inconsistent and confusing.

**Comment by kevmoo** [comment]
Sadly, we can only do as well as the discovery document we get from the API server. These details are not provided!
