### ISSUE TITLE
generated description super long

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/googleapis#3]
The generated description in the pubspec is super long:

![screen shot 2015-01-28 at 1 20 29 pm](https://cloud.githubusercontent.com/assets/1269969/5947294/c8043b5c-a6f0-11e4-95fa-efd6dbdcf80c.png)

Perhaps it shouldn't include the generated API names.

**Comment by kevmoo** [comment]
@jonasfj @mit-mit this would be GREAT to fix with the next release

**Comment by kevmoo** [comment]
This was fixed a while ago!
