### ISSUE TITLE
Contains code that uses dynamic as bottom

### ISSUE THREAD

**Issue by srawlins** [dart-lang/googleapis#31]
(Basically a sister issue for https://github.com/dart-lang/discoveryapis_generator/issues/181)

Once https://github.com/dart-lang/discoveryapis_generator/issues/181 is fixed, googleapis need to be regenerated with code that does not use dynamic as bottom, before Dart 2.0 is released. https://github.com/dart-lang/sdk/issues/29630

**Comment by jakobr-google** [comment]
There have been a number of Dart 2 fixes since, so this issue should be gone.
