### ISSUE TITLE
Calendar API Dart2/strong mode error: type '_InternalLinkedHashMap' is not a subtype of type 'Map<String, List<String>>'

### ISSUE THREAD

**Issue by pulyaevskiy** [dart-lang/googleapis#34]
I was so close to finally integrate calendar API in my project and then:

```
type '_InternalLinkedHashMap' is not a subtype of type 'Map<String, List<String>>' where
_InternalLinkedHashMap is from dart:collection
Map is from dart:core
String is from dart:core
List is from dart:core
String is from dart:core
#0      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:66:47)
#1      CalendarsResourceApi.insert (package:googleapis/calendar/v3.dart:1157:32)
#2      CalendarServer.createSecondaryCalendar (package:memspace/src/services/calendar_server.dart:35:26)
#3      _createCalendar (package:memspace/src/middleware/auth.dart:154:33)
<asynchronous suspension>
...
```

**Comment by pulyaevskiy** [comment]
https://github.com/dart-lang/discoveryapis_commons/pull/13 partially fixes this issue.

Remaining piece with this particular request is to update `ConferenceProperties.fromJson` to cast `List` to `List<String>`, e.g.:

```dart
ConferenceProperties.fromJson(core.Map _json) {
    if (_json.containsKey("allowedConferenceSolutionTypes")) {
      allowedConferenceSolutionTypes = new core.List<core.String>.from(
          _json["allowedConferenceSolutionTypes"]);
    }
  }
```

**Comment by zoechi** [comment]
I run into a similar problem 

_discoveryapis_commons-0.1.5/lib/src/clients.dart line 50
it specifies the parameter as `Map`

![image](https://user-images.githubusercontent.com/405837/37409274-36c57d18-279e-11e8-87b8-74a0f5813fcc.png)

but the `_request` method at line 129 requires a `Map<String, List<String>>`

![image](https://user-images.githubusercontent.com/405837/37409389-895d51ea-279e-11e8-81f1-01653009341b.png)

which causes an exception in Flutter with `--preview-dart-2`

**Comment by pulyaevskiy** [comment]
Yeah, you can try and add a `dependency_override` with the version from https://github.com/dart-lang/discoveryapis_commons/pull/13 that fixes this issue.

But I've found that the generated APIs have issues as well. Pretty much in every `fromJson` method which deals with `List`s.

For now I'm using the above mentioned override and just copied generated file for Calendar API to my project and fixing issues by hand one at a time.

**Comment by zoechi** [comment]
@pulyaevskiy thanks. I'll check what you suggest
