### ISSUE TITLE
Batch operations

### ISSUE THREAD

**Issue by HonzaKopecky** [dart-lang/googleapis#42]
I am trying to implement batch requests to Google Drive API to speed up analysis of folders structure. As I see it there is no way to perform batch requests using this library is that right?

Every request is performed right away (for examle https://pub.dartlang.org/documentation/googleapis/0.50.1/googleapis.drive.v3/FilesResourceApi/list.html) so there is no way to collect multiple "prepared" requests, join them together and send as one request to `https://www.googleapis-com/batch`, right?

**Comment by mkustermann** [comment]
That's correct, we don't have any batch support in the API generator (https://github.com/dart-lang/discoveryapis_generator). Also I think the `Future`-based interfaces might not easily allow for batching, because they are simply methods which return `Future<Response>`.

That being said, for more modern clients, which use http2, that might not be a big issue, since the underlying transport can handle potentially many http requests in parallel.

/cc @jakobr-google

**Comment by HonzaKopecky** [comment]
I would not say that it is not a problem in situation when I try to send potentially thousands of requests.

Anyway, thanks for the information, I have implemented batching myself.

**Comment by tonyshkurenko** [comment]
@HonzaKopecky how did you do that?

This article: https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html

says that 
> The Google API Dart Client Library does not support these features.

I need to use this api method: https://developers.google.com/gmail/api/v1/reference/users/messages/get

Do I need to send tons of getMessageById requests in parallel?

**Comment by HonzaKopecky** [comment]
Sorry for the late reply.

I had to stop using the Client Library. Instead I am sending the requests
in batches as described here:
https://developers.google.com/drive/api/v3/batch

My project is not available for public so I cannot share the repository
with you but I could send the files in question if you wish.

**Comment by tonyshkurenko** [comment]
Thanks for the reply :)

Seems like for me there is no such kind of api :(

**Comment by HonzaKopecky** [comment]
Google is discontinuing the global /batch/ endpoint so developers are asked
to migrate to service specific batch endpoints such as /batch/drive/v3/. I
would be surprised if there was not /batch/gmail/v1/.
