### ISSUE TITLE
404 When using clientViaServiceAccount

### ISSUE THREAD

**Issue by alexandrefett** [dart-lang/googleapis#50]
Hi, 
I followed the steps but I still having error.
I got DetailedApiRequestError(status: 404, message: Not Found) when tried to use auth.clientViaServiceAccount(credentials, scopes); 
If I use auth.clientViaUserConsent(id, scopes, prompt); (need a browser) works 100% fine

    print(client.credentials.accessToken.data); // token OK on both methods
    print(client.credentials.idToken); // null on both methods
    print(client.credentials.refreshToken); // null when ServiceAccount //OK when UserConsent

**Comment by konaken73** [comment]
Can you tell us how you made it?

**Comment by mkustermann** [comment]
Would you mind filing an issue at the [package:googleapis_auth](https://github.com/dart-lang/googleapis_auth) repository, since this repository is only for generated googleapis.

If possible also include detailed steps to reproduce, or at least understand, your problem.
