### ISSUE TITLE
Allow http versions >= 0.12.0

### ISSUE THREAD

**Issue by zanderso** [dart-lang/googleapis#56]
packge:flutter hardcodes 0.12.0: https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml#L39

**Comment by kevmoo** [comment]
How urgent is this, @zanderso ?

**Comment by sortie** [comment]
I don't have anything to do with this package.

**Comment by zanderso** [comment]
It's blocking third_party package rolls into Fuchsia, which blocks adding new third_party packages. It'd be great to get this resolved in the next couple days.

**Comment by mkustermann** [comment]
This repository contains generated apis which we publish on pub as well as some utility scripts. The actual constraint must be changed in the https://github.com/dart-lang/discoveryapis_generator repository.
