### ISSUE TITLE
After all this time, the Google Contacts API is still missing.

### ISSUE THREAD

**Issue by gmosx** [dart-lang/googleapis#6]
Is there a reason for it?

**Comment by sgjesse** [comment]
The scope of the googleapis package is to provide access to APIs exposed through the [Google API Discovery Service](https://developers.google.com/discovery/).

The Contacts API and a number of other APIs are [GData APIs](https://developers.google.com/gdata/docs/directory).

GData APIs are being replaced with newer APIs exposed through the Discovery Service, however for the Contacts API it seems that there are still no replacement ready.
