### ISSUE TITLE
CircularProgressIndicator ui stuck on IOS but works fine in andriod

### ISSUE THREAD

**Issue by laoniustudio** [dart-lang/googleapis#64]
```
Future<DriveApi> getDrive(String sth) async {
  final client = await clientViaServiceAccount(credentials, const [DriveApi.DriveScope]);
  final drive = DriveApi(client);
  return drive;
}
```
when I call the clientViaServiceAccount, CircularProgressIndicator stuck there but only happens on IOS 
device, and the problem is only on physics device, when i test on the simulator device on my mac, no problem. please help

**Comment by kevmoo** [comment]
Please try again with the latest API.
