### ISSUE TITLE
[cloud_speech] Streaming response support

### ISSUE THREAD

**Issue by rishab2113** [dart-lang/googleapis#66]
The cloud speech API supports streaming recognition via gRPC, but the dart cloud-speech package doesn't support streaming recognition, is there any planned support for this?

**Comment by rishab2113** [comment]
I've generated a library but have had issues getting it to work. [It's here!](https://github.com/rishab2113/cloud_speech/tree/master/example/lib/src/generated/google/cloud/speech/v1)

**Comment by felixjunghans** [comment]
To all who are still looking for speech functionality with streaming support. I have created a package for this purpose that supports grpc and communicates with Google's Speech-to-text api.

[You can find it here](https://pub.dev/packages/google_speech)
