### ISSUE TITLE
Firestore: Can't delete in a transaction

### ISSUE THREAD

**Issue by kentcb** [dart-lang/googleapis#69]
The [delete](https://github.com/dart-lang/googleapis/blob/master/generated/googleapis/lib/firestore/v1.dart#L928) method does not take a transaction ID, so there appears to be no way to delete a document within the context of a transaction.

**Comment by jonasfj** [comment]
Rest docs are here:
https://firebase.google.com/docs/firestore/reference/rpc/

This is an auto-generated client library...

In any case, see the commit method, it takes a list of deletes and updates..

**Comment by kentcb** [comment]
@jonasfj Yeah, I realize it's generated. However, it doesn't align with the Firebase API as used from a flutter app, so this difference confused matters. Also, I've found other problems with the generated code, such as #25 (which I'd appreciate your input on). Thanks for pointing me in the right direction.
