### ISSUE TITLE
Uploading files through DriveApi.files.create() on web

### ISSUE THREAD

**Issue by ggeorgiev92** [dart-lang/googleapis#74]
Is it possible to upload files from the WEB through googleapis DriveApi instance?
How to convert File() (dart instance) to media file which create method need?

I tried to read the file with FileReader() as readAsArrayBuffer or readAsDataUrl but in first case I'm receiving Uint8List, in second String (base64).

Part of my code:
```
final reader = new FileReader();
    reader.readAsDataUrl(file);
    reader.onLoad.listen((e) async{

      drive.File fileMetadata = drive.File.fromJson({
        "mimeType": file.type,
        "name": file.name,
        "parents": [folderId]
      });

      drive.Media fileMedia = drive.Media(reader.result, file.size, contentType: file.type);

      drive.DriveApi.files.create(fileMetadata, uploadMedia: fileMedia)
```

Issue here is that Media() want first parameter to be `async.Stream<core.List<core.int>>`;
Can someone give me a solution of creating a file from web with that google package?

pub dependencies: googleapis: ^0.52.0+1

**Comment by jonasfj** [comment]
If you need to create a `Stream<List<int>>` from a String you can just do:
```dart
import 'dart:convert';

final Stream<List<int>> stream = () async * {
  yield utf8.encode('hello-world');
}();
```

This is creating an async generator and calling it...

Is that what you're looking for?

**Comment by ggeorgiev92** [comment]
That's close to what I need. 
How can I do that magic with a File? I have file object - do I need to read it with FileReader() and if yes how? I tried with replace encode parameter with reader.result but the file was with broken encoding after that. Any idea?

**Comment by jonasfj** [comment]
I think this part has to do with `File` from `html:js`, probably it's something a long the lines of:
https://stackoverflow.com/a/15981017/68333

But I think that is outside the scope of this package.
