### ISSUE TITLE
Unable to call FirestoreApi.listen()

### ISSUE THREAD

**Issue by cachapa** [dart-lang/googleapis#77]
Calling FirestoreApi.listen() always returns `400 Bad Request`.

Unfortunately the documentation doesn't help much here, nor does the error message. From my investigation it seems I'm supplying all of the required parameters, though that's hard to say from just looking at the docs.

The following code shows the issue I'm having. This is on a database with open security rules:

``` dart
import 'package:googleapis/firestore/v1.dart';
import 'package:http/http.dart' as http;

final projectId = "PROJECT_ID";
final databaseId = "(default)";
final database = "projects/$projectId/databases/$databaseId";
final documentPath = "$database/documents/test_collection/test_document";

final firestore = FirestoreApi(http.Client());

Future main() async {
  // Works fine
  await getDocument();

  // Fails with 400 Bad Request
  await listen();
}

Future getDocument() async {
  var document = await firestore.projects.databases.documents.get(documentPath);
  print(document.fields["test_field"].stringValue);
}

Future listen() async {
  var documentsTarget = DocumentsTarget()
    ..documents = [documentPath];

  var target = Target()
    ..documents = documentsTarget;

  var listenRequest = ListenRequest()
    ..addTarget = target;

  var response = await firestore.projects.databases.documents
      .listen(listenRequest, database);
}
```

The outgoing json payload (collected using `listenRequest.toJson()`):
```
{
  addTarget: {
    documents: {
      documents: [
        projects/PROJECT_ID/databases/(default)/documents/test_collection/test_document
      ]
    }
  }
}
```

Here's the HTTP response:
```
<-- 400 Bad Request https://firestore.googleapis.com/v1/projects/PROJECT_ID/databases/(default)/documents:listen?alt=json
[
  {
    "error": {
      "code": 400,
      "message": "Invalid value (Object), ",
      "status": "INVALID_ARGUMENT",
      "details": [
        {
          "@type": "type.googleapis.com/google.rpc.BadRequest",
          "fieldViolations": [
            {
              "description": "Invalid value (Object), "
            }
          ]
        }
      ]
    }
  }
]
```

**Comment by jonasfj** [comment]
I'm wondering if:
A) this is exposed correctly in discovery API documents,
B) we are generating the correct code for the discovery API document,

Please feel free to dive deep and see if it's (A) or (B), the discovery API documents are documented in:
https://developers.google.com/discovery/v1/getting_started

I know we have some cases where our [generator](https://github.com/dart-lang/discoveryapis_generator) is not generating the write code.

**Comment by cachapa** [comment]
I was under the impression that this library implemented the gRPC version of the Google APIs, but if that's not the case (i.e. if it uses the REST interfaces) then this method will never work since it's not available via REST.

Though I supposed in that case the `listen()` method shouldn't be included in the library at all.

**Comment by jonasfj** [comment]
Yes, this is APIs for the REST API.

> Though I supposed in that case the `listen()` method shouldn't be included in the library at all.

That's a very good point :)

-----
If you want to use gRPC you can generate the APi yourself, the protobuf files should be available in:
https://github.com/googleapis/googleapis

**Comment by cachapa** [comment]
Thanks, I did generate the API myself but was having trouble with the `listen` call there as well, so I thought I'd try this one.

**Comment by guyluz11** [comment]
So are you intending on fixing it because this is in the office googleApis git or removing it because it is not REST API call?.
This is one of the most used features in Cloud FireStore and needed to take full control of the service.

**Comment by jonasfj** [comment]
I can try to inquire relevant parties if there is a way to remove it from the discovery document.

**Comment by jonasfj** [comment]
Update: It appears that `listen()` shouldn't have been listed in the discovery document.

**Comment by jonasfj** [comment]
We can't fix this issue in this package, it'll probably get fixed in the discovery document and then it'll land here some time after that.

**Comment by kevmoo** [comment]
Fix is now out in v7
