### ISSUE TITLE
static analysis issues (unused_*)

### ISSUE THREAD

**Issue by srawlins** [dart-lang/googleapis#80]
E.g.

```none
$ dartanalyzer lib/websecurityscanner/v1.dart 
Analyzing lib/websecurityscanner/v1.dart...
  hint • Unused import: 'dart:async'. • lib/websecurityscanner/v1.dart:8:8 • unused_import
  hint • The value of the field '_requester' isn't used. • lib/websecurityscanner/v1.dart:20:30 • unused_field
2 hints found.
```

**Comment by jonasfj** [comment]
I wonder if we can just tweak `analysis_options.yaml` to ignore this rather than fix it.

**Comment by srawlins** [comment]
That would fix it locally but not internally at Google. Inside Google we ban unused_import universally, even on "third party" packages which are synced into Google from outside.

**Comment by jonasfj** [comment]
We'll that's a solid argument :)

**Comment by kevmoo** [comment]
These are all fixed!
