### ISSUE TITLE
Drive API Download in bigger chunks

### ISSUE THREAD

**Issue by chitgoks** [dart-lang/googleapis#85]
Please add this option. The download takes very long for large files.
A way to set how much to download per chunk would be very helpful.

**Comment by jonasfj** [comment]
This is bindings for APIs exposed through https://developers.google.com/discovery

I'm not sure how to download, I would imagine it's done with:
https://pub.dev/documentation/googleapis/latest/googleapis.drive.v3/FilesResourceApi/get.html
