### ISSUE TITLE
Incomplete Cloud Tasks API (no HTTPRequest task object)

### ISSUE THREAD

**Issue by CosmicPangolin** [dart-lang/googleapis#89]
The HTTPRequest functionality in Cloud Tasks seems to be missing from the Dart library:

https://cloud.google.com/tasks/docs/reference/rest/v2/projects.locations.queues.tasks#HttpRequest

Only AppEngineHTTPRequest is included in the Task class.

Pretty blocked - I need a way of scheduling a Cloud Function for future execution from a Dart environment, as per:

https://medium.com/firebase-developers/how-to-schedule-a-cloud-function-to-run-in-the-future-in-order-to-build-a-firestore-document-ttl-754f9bf3214a

**Comment by kevmoo** [comment]
https://pub.dev/documentation/googleapis/latest/cloudtasks.v2/HttpRequest-class.html

I think this is fixed now. Take a look!
