### ISSUE TITLE
Can't insert CalendarList

### ISSUE THREAD

**Issue by tbm98** [dart-lang/googleapis#93]
my entry map
```
final Map<String, dynamic> calendarListEntry = {
    'accessRole': 'reader',
    'backgroundColor': '#16a765',
    'colorId': '8',
    'conferenceProperties': {
      'allowedConferenceSolutionTypes': ['eventHangout']
    },
    'defaultReminders': [
      {
        "method": 'popup',
        "minutes": 30
      }
    ],
    'etag': "${DateTime.now().microsecondsSinceEpoch}",
    'foregroundColor': '#000000',
    'id': 'student social',
    'kind': 'calendar#calendarListEntry',
    'selected': true,
    'summary': 'Lịch học được đồng bộ từ student social',
    'summaryOverride': 'Lịch học được đồng bộ từ student social',
    'timeZone': 'Asia/Ho_Chi_Minh'
  };
```
my code:
```
final calendarList = await calendarApi.calendarList
      .insert(CalendarListEntry.fromJson(calendarListEntry),colorRgbFormat: true);
```
my error:
```
E/flutter (11975): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DetailedApiRequestError(status: 404, message: Not Found)
E/flutter (11975): #0      _validateResponse (package:_discoveryapis_commons/src/clients.dart:852:9)
E/flutter (11975): <asynchronous suspension>
E/flutter (11975): #1      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:74:22)
E/flutter (11975): <asynchronous suspension>
E/flutter (11975): #2      CalendarListResourceApi.insert (package:googleapis/calendar/v3.dart:669:32)
E/flutter (11975): #3      signInWithGoogle (package:studentsocialgooglecalendar/google_sign_in_helper.dart:105:8)
```

It get list normal but can't insert.

**Comment by tbm98** [comment]
I was done by `calendarApi.calendars.insert`

**Comment by DenisMrGnusa** [comment]
same here,

this my error log

E/flutter (19032): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DetailedApiRequestError(status: 404, message: Not Found)
E/flutter (19032): #0      _validateResponse (package:_discoveryapis_commons/src/clients.dart:854:9)
E/flutter (19032): <asynchronous suspension>
E/flutter (19032): #1      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:76:22)
E/flutter (19032): <asynchronous suspension>
E/flutter (19032): #2      CalendarListResourceApi.insert (package:googleapis/calendar/v3.dart:669:32)
E/flutter (19032): #3      SignInDemoState._handleInsertCalendar (package:flutter_app_google_api_2/main.dart:62:30)
E/flutter (19032): <asynchronous suspension>
E/flutter (19032): #4      _CalendarFormState.build.<anonymous closure> (package:flutter_app_google_api_2/calendar_form.dart:86:42)
E/flutter (19032): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (19032): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (19032): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (19032): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (19032): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (19032): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (19032): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (19032): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (19032): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (19032): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (19032): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (19032): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (19032): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (19032): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (19032): #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (19032): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (19032): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (19032): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (19032): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (19032): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (19032): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (19032): #26     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (19032): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (19032):
