### ISSUE TITLE
Response Content-Type is different than Healthcare API v1 client is expecting

### ISSUE THREAD

**Issue by sarancibiao** [dart-lang/googleapis#99]
It's causing issues an ApiRequestError of  async.Future<HttpBody> Patient_everything method

**Error:** ApiRequestError(message: Unable to read response with content-type application/fhir+json;charset=utf-8.)

![image](https://user-images.githubusercontent.com/65574939/82270812-fb86de80-9943-11ea-9af2-4aed6bcbc1b3.png)
![image](https://user-images.githubusercontent.com/65574939/82271512-f9be1a80-9945-11ea-8038-e39a59c856a3.png)
![image](https://user-images.githubusercontent.com/65574939/82270674-8a472b80-9943-11ea-88aa-e3520b71d283.png)

**Comment by stevedj** [comment]
Hi @sarancibiao 

I also got this issue, when I want to create the FHIR Resources,
I think we should create the request with 
`    -H "Content-Type: application/fhir+json; charset=utf-8" \`
as described here, 
https://cloud.google.com/healthcare/docs/how-tos/fhir-resources#healthcare-create-patient-cli-curl
